export const RECHARGE_VISIBLE = 'RECHARGE_VISIBLE';
export const WITHDRAW_VISIBLE = 'WITHDRAW_VISIBLE';
export const WALLET_VISIBLE = 'WALLET_VISIBLE';

export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_INFO = 'PRODUCT_INFO';

export const POOL_LIST = 'POOL_LIST';

export const CURRENT_PERIOD = 'CURRENT_PERIOD';
