export const RECHARGE_VISIBLE = 'RECHARGE_VISIBLE';
export const WITHDRAW_VISIBLE = 'WITHDRAW_VISIBLE';
export const WALLET_VISIBLE = 'WALLET_VISIBLE';
export const TRANSACTION_HASH_VISIBLE = 'TRANSACTION_HASH_VISIBLE';

export const PRODUCT_LIST = 'PRODUCT_LIST';
export const TRADE_HISTORY_LIST = 'TRADE_HISTORY_LIST';
export const ADD_TRADE_HISTORY = 'ADD_TRADE_HISTORY';
export const REMOVE_TRADE_HISTORY = 'REMOVE_TRADE_HISTORY';
export const UPDATE_TRADE_HISTORY = 'UPDATE_TRADE_HISTORY';
export const PRODUCT_INFO = 'PRODUCT_INFO';

export const POOL_LIST = 'POOL_LIST';
export const POOL_INFO = 'POOL_INFO';

export const CURRENT_PERIOD = 'CURRENT_PERIOD';
export const TICKER_UPDATE = 'TICKER_UPDATE';
export const QUOTE = 'QUOTE';
